const mongoose = require('mongoose');
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

async function run() {
  await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/food-donation');
  console.log('Connected to MongoDB');

  // 1. Approve all NGO profiles and set user isVerified to true
  const updateNgoResult = await mongoose.connection.db.collection('ngoprofiles').updateMany(
    {},
    { $set: { verificationStatus: 'approved' } }
  );
  console.log('Updated NGO profiles verificationStatus to approved:', updateNgoResult.modifiedCount);

  await mongoose.connection.db.collection('users').updateMany(
    { role: 'ngo' },
    { $set: { isVerified: true } }
  );

  // 2. Remove automated test users generated by tests
  const deleteTestUsers = await mongoose.connection.db.collection('users').deleteMany({
    email: { $regex: '@test\\.com$' }
  });
  console.log('Deleted automated test users:', deleteTestUsers.deletedCount);

  // 3. Remove orphaned profiles whose user was deleted
  const validUsers = await mongoose.connection.db.collection('users').find({}).toArray();
  const validUserIds = validUsers.map(u => u._id);

  const deleteVolProfiles = await mongoose.connection.db.collection('volunteerprofiles').deleteMany({
    user: { $nin: validUserIds }
  });
  console.log('Deleted orphaned volunteer profiles:', deleteVolProfiles.deletedCount);

  const deleteNgoProfiles = await mongoose.connection.db.collection('ngoprofiles').deleteMany({
    user: { $nin: validUserIds }
  });
  console.log('Deleted orphaned NGO profiles:', deleteNgoProfiles.deletedCount);

  const remainingUsers = await mongoose.connection.db.collection('users').find({}).project({ name: 1, email: 1, role: 1 }).toArray();
  console.log('\n--- Current Real Users in DB ---');
  console.log(remainingUsers);

  const remainingVolProfiles = await mongoose.connection.db.collection('volunteerprofiles').find({}).toArray();
  console.log('\n--- Current Volunteer Profiles in DB ---');
  console.log(remainingVolProfiles);

  await mongoose.disconnect();
}

run();
